development:
  adapter: postgresql
  encoding: unicode
  database: simple_feedback_development
  pool: 5

test:
  adapter: postgresql
  encoding: unicode
  database: simple_feedback_test
  pool: 5

production:
  adapter: postgresql
  encoding: unicode
  database: simple_feedback_production
  pool: 5
